services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: banco_livraria
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=banco_livraria
      - DB_USER=usuario
      - DB_PASS=senha
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data: